```{r}
SD1_raw <- 
  read_excel(path = "./data/_raw/SD1_excel.xlsx", skip = 1)  %>% 
  write_csv2(file = "./data/SD1_converted.csv") %>% 
  as_tibble()
```

```{r}
SD1_clean <- 
  SD1_raw %>% 
  mutate(`Taxonomic classification` = str_replace_all(`Taxonomic classification`, pattern = "[:alpha:]__", "")) %>% 
  separate(col = `Taxonomic classification`, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = ';') %>% 
  na_if("")
SD1_clean
```

```{r}
SD1_table <- 
  SD1_clean %>%
  mutate(ISSCapoA1 = ISSCapoA1/sum(ISSCapoA1),
         ISSCapoA2 = ISSCapoA2/sum(ISSCapoA2),
         ISSCapoA3 = ISSCapoA3/sum(ISSCapoA3),
         ISSCapoA4 = ISSCapoA4/sum(ISSCapoA4),
         ISSCapoA5 = ISSCapoA5/sum(ISSCapoA5),
         ISSCapoA6 = ISSCapoA6/sum(ISSCapoA6),
         ISSCapoA7 = ISSCapoA7/sum(ISSCapoA7),
         ISSCapoA8 = ISSCapoA8/sum(ISSCapoA8),
         ISSCapoA9 = ISSCapoA9/sum(ISSCapoA9),
         ISSCapoB1 = ISSCapoB1/sum(ISSCapoB1),
         ISSCapoB2 = ISSCapoB2/sum(ISSCapoB2),
         ISSCapoB3 = ISSCapoB3/sum(ISSCapoB3),
         ISSCapoB4 = ISSCapoB4/sum(ISSCapoB4),
         ISSCapoB5 = ISSCapoB5/sum(ISSCapoB5),
         ISSCapoB6 = ISSCapoB6/sum(ISSCapoB6),
         ISSCapoB7 = ISSCapoB7/sum(ISSCapoB7),
         ISSCapoB8 = ISSCapoB8/sum(ISSCapoB8),
         ISSCapoC1 = ISSCapoC1/sum(ISSCapoC1),
         ISSCapoC2 = ISSCapoC2/sum(ISSCapoC2),
         ISSCapoC3 = ISSCapoC3/sum(ISSCapoC3),
         ISSCapoC4 = ISSCapoC4/sum(ISSCapoC4),
         ISSCapoC5 = ISSCapoC5/sum(ISSCapoC5),
         ISSCapoC6 = ISSCapoC6/sum(ISSCapoC6),
         ISSCapoC7 = ISSCapoC7/sum(ISSCapoC7))
```

```{r}
SD1_data_pivot_longer <- SD1_table %>% 
  pivot_longer(names_to = "ISSCapoA", values_to = "ValueA", ISSCapoA1 : ISSCapoA9) %>%
  pivot_longer(names_to = "ISSCapoB", values_to = "ValueB", ISSCapoB1 : ISSCapoB8) %>%
  pivot_longer(names_to = "ISSCapoC", values_to = "ValueC", ISSCapoC1 : ISSCapoC7)
```

```{r}
SD1_data_rename <- SD1_data_pivot_longer %>%
  mutate(ISSCapoA = str_replace_all(ISSCapoA, pattern = c('ISSCapoA1' = "Columbus RGSH", 
                                                          'ISSCapoA2' = "Columbus SCC laptop",
                                                          'ISSCapoA3' = "Columbus handrails", 
                                                          'ISSCapoA4' = "Columbus light cover", 
                                                          'ISSCapoA5' = "Columbus air", 
                                                          'ISSCapoA6' = "Node2 sleeping unit",
                                                          'ISSCapoA7' = "Node2 panel outside",
                                                          'ISSCapoA8' = "Node2 ATU",
                                                          'ISSCapoA9' = "Node2 RGSH")),
         ISSCapoB = str_replace_all(ISSCapoB, pattern = c('ISSCapoB1' = "Columbus RGSH", 
                                                          'ISSCapoB2' = "Columbus SCC laptop",
                                                          'ISSCapoB3' = "Columbus handrails", 
                                                          'ISSCapoB4' = "Columbus light cover", 
                                                          'ISSCapoB5' = "Columbus air", 
                                                          'ISSCapoB6' = "Node2 sleeping unit",
                                                          'ISSCapoB7' = "Node2 panel outside",
                                                          'ISSCapoB8' = "Node2 ATU")),
         ISSCapoC = str_replace_all(ISSCapoC, pattern = c('ISSCapoC1' = "Columbus RGSH", 
                                                          'ISSCapoC2' = "Columbus SCC laptop",
                                                          'ISSCapoC3' = "Columbus handrails", 
                                                          'ISSCapoC4' = "Columbus light cover" , 
                                                          'ISSCapoC5' = "Columbus air", 
                                                          'ISSCapoC6' = "Node2 sleeping unit",
                                                          'ISSCapoC7' = "Node2 panel outside")))
```


```{r}
pl1 <- SD1_data_rename %>%
  ggplot(mapping = aes(x = ISSCapoA,
                       y = ValueA,
                       fill = Domain)) + 
  geom_bar(position = "fill", 
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session A",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("lightblue", 
                               "deepskyblue4"))
pl1
```

```{r}
pl2 <- SD1_data_rename %>%
  ggplot(mapping = aes(x = ISSCapoB,
                       y = ValueB,
                       fill = Domain)) + 
  geom_bar(position = "fill", 
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session B",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("lightblue", 
                               "deepskyblue4"))
pl2
```


```{r}
pl3 <- SD1_data_rename %>%
  ggplot(mapping = aes(x = ISSCapoC,
                       y = ValueC,
                       fill = Domain)) + 
  geom_bar(position = "fill", 
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session C",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("lightblue", 
                               "deepskyblue4"))
pl3
```



```{r}
pl1 + pl2 + pl3
```

```{r}
pl4 <- SD1_data_rename %>%
  filter(Phylum == "Actinobacteria"| 
         Phylum == "Bacteroidetes"| 
         Phylum == "Firmicutes"| 
         Phylum == "Proteobacteria") %>%
  ggplot(mapping = aes(x = ISSCapoA,
                       y = ValueA,
                       fill = Phylum)) + 
  geom_bar(position = "fill", 
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session A",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("khaki3", "coral1", "orange1", "darkorchid4"))
pl4
```


```{r}
pl5 <- SD1_data_rename %>%
  filter(Phylum == "Actinobacteria"| 
         Phylum == "Bacteroidetes"| 
         Phylum == "Firmicutes"| 
         Phylum == "Proteobacteria") %>%
  ggplot(mapping = aes(x = ISSCapoB,
                       y = ValueB,
                       fill = Phylum)) + 
  geom_bar(position = "fill", 
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session B",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("khaki3", "coral1", "orange1", "darkorchid4"))
pl5
```


```{r}
pl6 <- SD1_data_rename %>%
  filter(Phylum == "Actinobacteria"| 
         Phylum == "Bacteroidetes"| 
         Phylum == "Firmicutes"| 
         Phylum == "Proteobacteria") %>%
  ggplot(mapping = aes(x = ISSCapoC,
                       y = ValueC,
                       fill = Phylum)) + 
  geom_bar(position = "fill", 
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session C",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("khaki3", "coral1", "orange1", "darkorchid4"))
pl6
```

```{r}
pl4 + pl5 + pl6
```


```{r}
pl7 <- SD1_data_rename %>%
  replace_na(list(Genus = 'Unknown')) %>%
  filter(Genus == "Streptococcus" | 
         Genus == "Corynebacterium" | 
         Genus == "Lactobacillus" | 
         Genus == "Acinetobacter" | 
         Genus == "Staphylococcus" | 
         Genus == "Unknown") %>%
  select(Genus, ISSCapoA, ValueA) %>% 
  ggplot(mapping = aes(x = ISSCapoA,
                       y = ValueA, 
                       fill = Genus)) + 
  geom_bar(position = "fill",
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session A",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("khaki2", "palevioletred3", "skyblue", "orange", "violet", "turquoise4"))
pl7
```

```{r}
pl8 <- SD1_data_rename %>%
  replace_na(list(Genus = 'Unknown')) %>%
  filter(Genus == "Streptococcus" | 
         Genus == "Corynebacterium" | 
         Genus == "Lactobacillus" | 
         Genus == "Acinetobacter" | 
         Genus == "Staphylococcus" | 
         Genus == "Unknown") %>%
  select(Genus, ISSCapoB, ValueB) %>% 
  ggplot(mapping = aes(x = ISSCapoB,
                       y = ValueB, 
                       fill = Genus)) + 
  geom_bar(position = "fill",
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session B",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("khaki2", "palevioletred3", "skyblue", "orange", "violet", "turquoise4"))
pl8
```

```{r}
pl9 <- SD1_data_rename %>%
  replace_na(list(Genus = 'Unknown')) %>%
  filter(Genus == "Streptococcus" | 
         Genus == "Corynebacterium" | 
         Genus == "Lactobacillus" | 
         Genus == "Acinetobacter" | 
         Genus == "Staphylococcus" | 
         Genus == "Unknown") %>%
  select(Genus, ISSCapoC, ValueC) %>% 
  ggplot(mapping = aes(x = ISSCapoC,
                       y = ValueC, 
                       fill = Genus)) + 
  geom_bar(position = "fill",
           stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "ISS session C",
       y = "Abundance (TSS)") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("khaki2", "palevioletred3", "skyblue", "orange", "violet", "turquoise4"))
pl9
```

```{r}
pl7 + pl8 + pl9
```


