---
title: "ISS"
author: "Prince"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load library, include=FALSE}
library(tidyverse)
library(readxl)
library(hilldiv)
```

# 01_load.R
```{r load excel, convert to csv, load as R object}
SD1_raw <- 
  read_excel(path = "./data/SD1_excel.xlsx", skip = 1) %>% 
  write_csv2(file = "./data/SD1_converted.csv") %>% 
  as_tibble()
```

# 02_clean.R
## Expand Taxonomic classification to Domain, Phylum and Genus, according to RSV ID

Isolated column test - SUCCESS
```{r isolate tax class test}
SD1_raw %>%
  select(`Taxonomic classification`) %>% 
  as_tibble() %>% 
  mutate(`Taxonomic classification` = str_replace_all(`Taxonomic classification`, pattern = "[:alpha:]__", "")) %>% 
  separate(col = `Taxonomic classification`, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = ';') %>% 
  na_if("") %>% 
  select(-Class, -Order, -Family, -Species)
```
 
Final iteration of column expansion
```{r remove "[:alpha:]__" pattern and separate based on semi colon, drop NAs}
SD1_clean <- 
  SD1_raw %>% 
  mutate(`Taxonomic classification` = str_replace_all(`Taxonomic classification`, pattern = "[:alpha:]__", "")) %>% 
  separate(col = `Taxonomic classification`, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = ';') %>% 
  na_if("")
SD1_clean
```

Saving clean data as csv
```{r} save expanded data to csv} 
SD1_clean %>% write_csv2(file = "./data/SD1_clean.csv")
```

Store clean data as new R object
```{r Store clean data as R object}
SD1_clean_fig1 <-
  SD1_clean %>% 
  select(-Class, -Order, -Family, -Species)
```

## Import and tidy TABLE 1
```{r load table 1}
table1 <- tribble(
  ~Wipe, ~Sampled_surface, ~ISS_module, ~Session,
  c("A-5,B-1"), "Ambient air (field blank, FB)", "Columbus", c("A,B"),
  c("A-4,B-2"), "Light covers", "Columbus", c("A,B"),
  c("A-2,B-3"), "SCC laptop", "Columbus", c("A,B"),
  c("A-3,B-4"), "Hand grips", "Columbus", c("A,B"),
  c("A-1,B-5"), "Return Grid Sensor Housing (RGSH)", "Columbus", c("A,B"),
  c("A-6,B-6"), "Sleeping unit", "Node 2", c("A,B"),
  c("A-7,B-7"), "Panels (outer surface, close to the Portable Fire Extinguisher (PFA) and Portable Breathing", "Node 2", c("A,B"),
  c("A-8,B-8"), "Audio Terminal Unit (ATU)", "Node2", c("A,B"),
"A-9", "Return Grid Sensor Housing (RGSH)", "Node 2", "A",
"C-1", "Ambient air (field blank, FB)", "Cupola", "C",
"C-2", "Surface facing a window", "Cupola", "C",
"C-3", "Advanced Resistive Exercise Device (ARED)", "Node 3", "C",
"C-4", "Treadmill", "Node 3", "C", 
"C-5", "Waste and Hygiene Compartment (WHC): surfaces", "Node 3", "C",
"C-6", "Cover of the PBA, inside", "Node 1", "C", 
"C-7", "Dining table", "Node 1", "C")
```

```{r tidy table 1 via removing "-" string, separate and pivotting}
table1_tidy <- 
table1 %>% 
  mutate(`Wipe` = str_replace_all(`Wipe`, pattern = "-", "")) %>% 
  separate(col = Wipe, into = c("Wipe1", "Wipe2"), sep = ",") %>% 
  separate(col = Session, into = c("Session1", "Session2"), sep = ",") %>% 
  pivot_longer(cols = c("Wipe1", "Wipe2"), values_to = "Wipe") %>% 
  select(-name) %>% 
  pivot_longer(cols = c("Session1", "Session2"), values_to = "Session") %>% 
  select(-name) %>% 
  drop_na()
```
## join with table1_tidy [DOESN'T WORK]
```{r join SD1 and table1}
#inner_join(SD1_clean, table1_tidy, by = Wipe)
```

## Isolate and Plot Session A
```{r Isolating Session A}
SD1_clean_fig1_A <-
SD1_clean_fig1 %>% 
  select(-starts_with("ISSCapoC"), 
         -starts_with("ISSCapoB")) %>% 
  rename("Columbus RGSH" = ISSCapoA1,
         "SCC laptop" = ISSCapoA2,
         "Hand grips" = ISSCapoA3,
         "Light covers" = ISSCapoA4,
         "Ambient air (field blank, FB)" = ISSCapoA5,
         "Sleeping unit" = ISSCapoA6,
         "Panels" = ISSCapoA7,
         "Audio Terminal Unit (ATU)" = ISSCapoA8,
         "Node 2 RGSH" = ISSCapoA9,
         )
```


```{r}
df <- tibble(x = c(1, 2, NA), y = c("a", NA, "b"))
df %>% 
  drop_na()

df %>% 
  mutate(x = replace_na(x, 0),
         y = replace_na(y, 0))
```

``` {r tss calculation}
#Sums to 1
SD1_clean_fig1_A %>% 
  select(`Columbus RGSH`) %>% 
  tss() %>% 
  sum()

#Sums to fuck knows
SD1_clean_fig1_A %>% 
  select(`Columbus RGSH`) %>% 
  sum()
```
# 03_data_analysis_I.R
```{r Figure 1 Session A Phylum plot GROUP WORK}
SD1_clean_fig1_A %>% 
  filter(Phylum == c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria")) %>% 
  mutate(`Columbus RGSH` = tss(`Columbus RGSH`),
         `SCC laptop` = tss(`SCC laptop`),
         `Hand grips` = tss(`Hand grips`),
         `Light covers` = tss(`Light covers`),
         `Ambient air (field blank, FB)` = tss(`Ambient air (field blank, FB)`),
         `Sleeping unit` = tss(`Sleeping unit`),
         `Panels` = tss(`Panels`),
         `Audio Terminal Unit (ATU)` = tss(`Audio Terminal Unit (ATU)`),
         `Node 2 RGSH` = tss(`Node 2 RGSH`)) %>% 
  pivot_longer(cols = Session_A_cols, names_to = "Surface", values_to = "Count") %>% 
  ggplot(mapping = 
         aes(y = Count,
             x = Surface,
             fill = Phylum)) + 
  geom_bar(position = "stack", stat = "identity") +
  scale_y_continuous(labels = scales::percent)
```


```{r Fig 1 Session A Phylum Plot}
#The scales are fucked up
Session_A_cols <- c("Columbus RGSH", "SCC laptop", "Hand grips", "Light covers", "Ambient air (field blank, FB)", "Sleeping unit", "Panels", "Audio Terminal Unit (ATU)", "Node 2 RGSH")

SD1_clean_fig1_A %>% 
  pivot_longer(cols = Session_A_cols, names_to = "Surface", values_to = "Count") %>% 
  filter(Phylum == c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria")) %>% 
  mutate(Count = tss(Count)) %>%
  ggplot(mapping = 
         aes(y = Count,
             x = Surface,
             fill = Phylum)) + 
  geom_bar(position = "stack", stat = "identity") +
  scale_y_continuous(labels = scales::percent)
```

```{r Fig 1 Session A Genus Plot}
#Data is completely fucked
Session_A_cols <- c("Columbus RGSH", "SCC laptop", "Hand grips", "Light covers", "Ambient air (field blank, FB)", "Sleeping unit", "Panels", "Audio Terminal Unit (ATU)", "Node 2 RGSH")

SD1_clean_fig1_A %>% 
  pivot_longer(cols = Session_A_cols, names_to = "Surface", values_to = "Count") %>% 
  mutate(Count = tss(Count)) %>% 
  filter(Genus == c("Streptococcus", "Corynebacterium", "Lactobacillus", "Acinetobacter", "Staphylococcus", "NA")) %>% 
  ggplot(mapping = 
         aes(y = Count,
             x = Surface,
             fill = Genus)) + 
  geom_bar(position = "stack", stat = "identity")
```